
    catch (int a) {
        //blok ini akan di ekskusi
        cout << "Pengecualian akan diekskusi" << endl;
    }
}